### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'TempRefrigerator_C'

### ISSUE THREAD

**Issue by blitzdakka** [nVuln/homebridge-lg-thinq#75]
**Describe The Bug:**
When adding a GF-B590PL refrigerator, the subject error is thrown.

**To Reproduce:**
Fresh install of HomeBridge, add plugin, have fridge included in accessories

**Expected behavior:**
Fridge to add successfully

**Logs:**

Starting to advertise 'Homebridge 7273 6670' using bonjour-hap backend!
[07/09/2021, 2:12:40 pm] Homebridge v1.3.4 (Homebridge 7273) is running on port 51601.

<< I've excluded the logs for my washer/dryer here, happy to provide if they'll add value, but I have no issues with those >>

[07/09/2021, 2:12:50 pm] [LGThinQ] Adding new accessory: Refrigerator
(node:30564) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'TempRefrigerator_C' in undefined
    at DeviceModel.monitoringValueMapping (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/DeviceModel.ts:160:14)
    at Refrigerator.createThermostat (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:212:53)
    at Refrigerator.createThermostat (/usr/lib/node_modules/homebridge-lg-thinq/src/v1/devices/Refrigerator.ts:12:18)
    at new Refrigerator (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:35:31)
    at new Refrigerator (/usr/lib/node_modules/homebridge-lg-thinq/src/v1/devices/Refrigerator.ts:5:1)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:125:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:53:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Plugin Config:**

{
    "bridge": {
        "name": "Homebridge 7273",
        "username": "----",
        "port": 51601,
        "pin": "----"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "country": "AU",
            "language": "en-AU",
            "auth_mode": "token",
            "refresh_token": "----",
            "username": "----",
            "password": "----",
            "devices": [
                {
                    "id": "1d6c7777-bf6c-1353-95a9-24e853db5e46",
                    "name": "Dryer",
                    "type": "DRYER"
                },
                {
                    "id": "d0f9c37a-42b9-1879-a103-dc039838787d",
                    "name": "Washer",
                    "type": "WASHER",
                    "washer_trigger": true,
                    "washer_door_lock": true
                },
                {
                    "id": "d74ed200-a234-11eb-8ae0-0051eda83e50",
                    "name": "Refrigerator",
                    "type": "REFRIGERATOR",
                    "ref_express_freezer": false,
                    "ref_express_fridge": false,
                    "ref_eco_friendly": false
                }
            ],
            "refresh_interval": 60,
            "thinq1": true,
            "platform": "LGThinQ"
        }
    ]
}

**Screenshots:**

N/A

**Environment:**

* **Plugin Version**: 1.1.4
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.17.6
* **NPM Version**: 6.14.15
* **Operating System**: Debian 11 in a Proxmox VM

**Comment by nVuln** [comment]
turn on homebridge debug mode, you can see something like this in debug log `Found device: {"deviceId":"09b19bb0-xxxxxx"}` , please upload it

**Comment by blitzdakka** [comment]
Oh sorry, didn't realise I'd missed that part of the log, here it is:

[07/09/2021, 2:12:48 pm] [LGThinQ] Found device:  {"deviceId":"d74ed200-a234-11eb-8ae0-0051eda83e50","deviceType":101,"modelName":"2REF12EBN_N_2","subModelNm":null,"sensorType":null,"alias":"Refrigerator","deviceCode":"KI0102","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"Onyxia","timezoneCode":"Australia/Sydney","timezoneCodeAlias":"AUS/Sydney","sdsGuide":"{\"deviceCode\":\"KI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"22889","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210906094159000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"1.2","modelJsonUri":"https://kic.lgthinq.com:46030/api/webContents/modelJSON?modelName=2REF12EBN_N_2&countryCode=WW&contentsId=JS0331222317133397&authKey=thinq","appModuleVer":"303.20","appModuleUri":"https://objectcontent.lgthinq.com/564c4846-f80f-4865-9372-31160a1010ed?hdnts=exp=1684281366~hmac=a0802768ae20ee30aa6d9154e23878212b6f5a87aff505bb35aafd7d4d3f9561","appRestartYn":"Y","appModuleSize":"7337592","langPackProductTypeVer":"47.3","langPackProductTypeUri":"https://objectcontent.lgthinq.com/2ed8fbe4-6e43-4d38-9a66-e4d302172c17?hdnts=exp=1694052592~hmac=284feecaba8bcd0445d21b20b632cf91289615b935002a4d838df33ccfa9f6d0","langPackModelVer":"","langPackModelUri":"","roomId":"163092222846194252","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"QC_Modem_1.2.80","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:RFBFMD-M:4D-P:P_NEXT8","cardType":"Small","cardControl":"Base"}

**Comment by nVuln** [comment]
I published a test version `v1.2.0-test.12`, please try install and see if it's worked

**Comment by blitzdakka** [comment]
The fridge is now connecting to HomeBridge and shows in HomeKit, but when I access it in the Home app it shows an error and I get errors in the HB log (pasted below). It also looked like the temps were off in the app, 3º higher for the fridge and 1º higher for the freezer compared to what the fridge actually displays.

[07/09/2021, 7:00:31 pm] [LGThinQ] Found device:  {"deviceId":"d74ed200-a234-11eb-8ae0-0051eda83e50","deviceType":101,"modelName":"2REF12EBN_N_2","subModelNm":null,"sensorType":null,"alias":"Refrigerator","deviceCode":"KI0102","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"Onyxia","timezoneCode":"Australia/Sydney","timezoneCodeAlias":"AUS/Sydney","sdsGuide":"{\"deviceCode\":\"KI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"22889","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210906094159000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"1.2","modelJsonUri":"https://kic.lgthinq.com:46030/api/webContents/modelJSON?modelName=2REF12EBN_N_2&countryCode=WW&contentsId=JS0331222317133397&authKey=thinq","appModuleVer":"303.20","appModuleUri":"https://objectcontent.lgthinq.com/564c4846-f80f-4865-9372-31160a1010ed?hdnts=exp=1684281366~hmac=a0802768ae20ee30aa6d9154e23878212b6f5a87aff505bb35aafd7d4d3f9561","appRestartYn":"Y","appModuleSize":"7337592","langPackProductTypeVer":"47.3","langPackProductTypeUri":"https://objectcontent.lgthinq.com/2ed8fbe4-6e43-4d38-9a66-e4d302172c17?hdnts=exp=1694052592~hmac=284feecaba8bcd0445d21b20b632cf91289615b935002a4d838df33ccfa9f6d0","langPackModelVer":"","langPackModelUri":"","roomId":"163092222846194252","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"QC_Modem_1.2.80","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:RFBFMD-M:4D-P:P_NEXT8","cardType":"Small","cardControl":"Base"}
[07/09/2021, 7:00:33 pm] [LGThinQ] Restoring existing accessory from cache: Refrigerator
[07/09/2021, 7:00:33 pm] [LGThinQ] START polling device data.
[07/09/2021, 7:00:56 pm] [homebridge-lg-thinq] This plugin threw an error from the characteristic 'Target Temperature': Unhandled error thrown inside write handler for characteristic: Cannot read property 'options' of null. See https://git.io/JtMGR for more info.
[07/09/2021, 7:00:56 pm] [homebridge-lg-thinq] TypeError: Cannot read property 'options' of null
    at DeviceModel.enumValue (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/DeviceModel.ts:133:51)
    at DeviceModel.lookupMonitorName (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/DeviceModel.ts:185:19)
    at TargetTemperature.setHandler (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:231:43)
    at TargetTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1588:42)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at TargetTemperature.Characteristic.handleSetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:791:24)
(node:34289) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of null
    at DeviceModel.enumValue (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/DeviceModel.ts:133:51)
    at DeviceModel.lookupMonitorName (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/DeviceModel.ts:185:19)
    at Status.get isExpressModeOn [as isExpressModeOn] (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:286:56)
    at Refrigerator.updateAccessoryCharacteristic (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:114:83)
    at EventEmitter.emit (events.js:400:28)
    at /usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:167:25
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34289) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:34289) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nVuln** [comment]
please try `v1.2.0-test.13`

**Comment by blitzdakka** [comment]
Connects and works fine but I get some errors when changing settings etc.

Turning express freeze on then off:
[07/09/2021, 9:23:51 pm] [LGThinQ] Unknown Error:  TokenError: 9000 - 잘못된 요청
    at /usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:254:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at API.thinq1PostRequest (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:244:12)
    at ThinQ.thinq1DeviceControl (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:173:14)
[07/09/2021, 9:24:02 pm] [LGThinQ] Unknown Error:  TokenError: 9000 - 잘못된 요청
    at /usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:254:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at API.thinq1PostRequest (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:244:12)
    at ThinQ.thinq1DeviceControl (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:173:14)


Changing temp:
[07/09/2021, 9:25:51 pm] [homebridge-lg-thinq] This plugin threw an error from the characteristic 'Target Temperature': Unhandled error thrown inside write handler for characteristic: Cannot read property 'options' of null. See https://git.io/JtMGR for more info.
[07/09/2021, 9:25:51 pm] [homebridge-lg-thinq] TypeError: Cannot read property 'options' of null
    at DeviceModel.enumValue (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/DeviceModel.ts:133:51)
    at DeviceModel.lookupMonitorName (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/DeviceModel.ts:185:19)
    at TargetTemperature.setHandler (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:231:43)
    at TargetTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1588:42)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at TargetTemperature.Characteristic.handleSetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:791:24)

It also doesn't seem to reflect changes in HomeKit, if I open the fridge door or change the temperature then HomeKit doesn't register it, although that doesn't result in an error in HB.

**Comment by nVuln** [comment]
I already published `v1.2.0-test.14` to fix some error

> It also doesn't seem to reflect changes in HomeKit, if I open the fridge door or change the temperature then HomeKit doesn't register it, although that doesn't result in an error in HB.

status is not update in realtime, default refresh interval is 60s

**Comment by blitzdakka** [comment]
> default refresh interval is 60s

Right that makes sense, yes temps are updating in HomeKit after waiting 60secs. The temps are still off but not by a set amount, they seem to get further off the more I change them on the fridge.

(Thanks for the continued troubleshooting btw!)

Still getting errors when changing settings or temperatures via HomeKit.

[07/09/2021, 10:32:55 pm] [LGThinQ] Unknown Error:  TokenError: 9000 - 잘못된 요청
    at /usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:254:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at API.thinq1PostRequest (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:244:12)
    at ThinQ.thinq1DeviceControl (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:173:14)
[07/09/2021, 10:43:30 pm] [LGThinQ] Unknown Error:  TokenError: 9000 - 잘못된 요청
    at /usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:254:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at API.thinq1PostRequest (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:244:12)
    at ThinQ.thinq1DeviceControl (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:173:14)
    at Refrigerator.setTemperature (/usr/lib/node_modules/homebridge-lg-thinq/src/v1/devices/Refrigerator.ts:17:5)
    at TargetTemperature.setHandler (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:240:9)

**Comment by nVuln** [comment]
> Still getting errors when changing settings or temperatures via HomeKit.
> 
> [07/09/2021, 10:32:55 pm] [LGThinQ] Unknown Error: TokenError: 9000 - 잘못된 요청
> at /usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:254:19
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
> at API.thinq1PostRequest (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:244:12)
> at ThinQ.thinq1DeviceControl (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:173:14)
> [07/09/2021, 10:43:30 pm] [LGThinQ] Unknown Error: TokenError: 9000 - 잘못된 요청
> at /usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:254:19
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
> at API.thinq1PostRequest (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:244:12)
> at ThinQ.thinq1DeviceControl (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:173:14)
> at Refrigerator.setTemperature (/usr/lib/node_modules/homebridge-lg-thinq/src/v1/devices/Refrigerator.ts:17:5)
> at TargetTemperature.setHandler (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:240:9)

ops, not sure why you got this error, because this error only happened when account don't have permission to control device
do you know how to capture network traffic? please try capturing traffic when control your refrigerator from native LG thinq app

**Comment by blitzdakka** [comment]
I'm familiar with the concept but haven't really done any before. I've tried poking around with Wireshark but it doesn't seem to capture any events related to me changing settings in the app. If you can give me some pointers (software/settings) happy to capture whatever I can.

**Comment by nVuln** [comment]
> I'm familiar with the concept but haven't really done any before. I've tried poking around with Wireshark but it doesn't seem to capture any events related to me changing settings in the app. If you can give me some pointers (software/settings) happy to capture whatever I can.

If you using mac os, proxy.man is easiest to use
Or Fiddler on windows may good choose

Wireshark is for professional only 🥲

**Comment by blitzdakka** [comment]
Oh wow, that proxyman is really cool. So I used that and made a few changes via the LG app, and now have a bunch of request logs for kic.lgthinq.com and a couple for kic-lgthinq.com.

This is one example log for kic.lgthinq.com:

{"id":"266","isIntercepted":true,"fileName":null,"style":null,"requestEndAt":null,"isUnderNetworkCondition":false,"isRelayed":false,"remoteDevice":{"ip":"127.0.0.1","name":"127.0.0.1"},"createAt":1631073470.1542411,"isSSL":true,"endAt":null,"summary":{"serverIpAddress":"","clientPort":57891,"clientIpAddress":"127.0.0.1","serverPort":0},"proxyCreatedAt":1631073470.1536732,"websocketMessageStorage":null,"request":{"port":46030,"method":{"name":"POST"},"header":{"entries":[{"key":{"name":"Host","nameInLowercase":"host"},"value":"kic.lgthinq.com:46030","isNewEntry":false},{"key":{"name":"Cookie","nameInLowercase":"cookie"},"value":"dtCookie=76B1D6D3CD838747AF8A1EC018373682|X2RlZmF1bHR8MQ","isNewEntry":false},{"key":{"name":"User-Agent","nameInLowercase":"user-agent"},"value":"Mozilla\/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit\/605.1.15 (KHTML, like Gecko) Mobile\/15E148","isNewEntry":false},{"key":{"name":"Accept-Encoding","nameInLowercase":"accept-encoding"},"value":"gzip, deflate, br","isNewEntry":false},{"key":{"name":"x-thinq-app-ver","nameInLowercase":"x-thinq-app-ver"},"value":"3.6.1200","isNewEntry":false},{"key":{"name":"x-thinq-app-type","nameInLowercase":"x-thinq-app-type"},"value":"NUTS","isNewEntry":false},{"key":{"name":"x-language-code","nameInLowercase":"x-language-code"},"value":"en-AU","isNewEntry":false},{"key":{"name":"Origin","nameInLowercase":"origin"},"value":"file:\/\/","isNewEntry":false},{"key":{"name":"x-client-id","nameInLowercase":"x-client-id"},"value":"00f38e1e7e1859b8892c25cde99c25e0fac55514e3c651c659bf455425573774","isNewEntry":false},{"key":{"name":"x-thinq-app-level","nameInLowercase":"x-thinq-app-level"},"value":"PRD","isNewEntry":false},{"key":{"name":"Content-Length","nameInLowercase":"content-length"},"value":"142","isNewEntry":false},{"key":{"name":"Connection","nameInLowercase":"connection"},"value":"keep-alive","isNewEntry":false},{"key":{"name":"x-user-no","nameInLowercase":"x-user-no"},"value":"AU2108204318026","isNewEntry":false},{"key":{"name":"x-service-code","nameInLowercase":"x-service-code"},"value":"SVC202","isNewEntry":false},{"key":{"name":"Accept-Language","nameInLowercase":"accept-language"},"value":"en-au","isNewEntry":false},{"key":{"name":"x-message-id","nameInLowercase":"x-message-id"},"value":"u8j3DR5MH6eGPI5ZSnsmi.","isNewEntry":false},{"key":{"name":"x-emp-token","nameInLowercase":"x-emp-token"},"value":"2e1fc58fd1f6f2f0b897b5c7e6f60cf99926ecc9c93a1304679acf116123f04a9dcf687005655d04b12880265f748c37","isNewEntry":false},{"key":{"name":"Accept","nameInLowercase":"accept"},"value":"application\/json","isNewEntry":false},{"key":{"name":"Content-Type","nameInLowercase":"content-type"},"value":"application\/json;charset=UTF-8","isNewEntry":false},{"key":{"name":"x-api-key","nameInLowercase":"x-api-key"},"value":"VGhpblEyLjAgU0VSVklDRQ==","isNewEntry":false},{"key":{"name":"x-thinq-app-os","nameInLowercase":"x-thinq-app-os"},"value":"IOS","isNewEntry":false},{"key":{"name":"x-country-code","nameInLowercase":"x-country-code"},"value":"AU","isNewEntry":false},{"key":{"name":"x-service-phase","nameInLowercase":"x-service-phase"},"value":"OP","isNewEntry":false}]},"fullPath":"https:\/\/kic.lgthinq.com:46030\/api\/rti\/rtiMon","scheme":"https","isWebSocketUpgrade":false,"isSSL":true,"host":"kic.lgthinq.com","version":{"major":1,"minor":1},"uri":"\/api\/rti\/rtiMon","bodyData":"eyJsZ2VkbVJvb3QiOnsiZGV2aWNlSWQiOiJkNzRlZDIwMC1hMjM0LTExZWItOGFlMC0wMDUxZWRhODNlNTAiLCJ3b3JrSWQiOiI3NTNhMTRlMS01ZGM4LTkzZTgtY2U5Yi02MTU2NTEyYWJhZGMiLCJjbWQiOiJNb24iLCJjbWRPcHQiOiJTdGFydCJ9fQ=="},"response":{"status":{"phrase":"OK","strict":false,"code":200},"bodyData":"eyJsZ2VkbVJvb3QiOnsicmV0dXJuQ2QiOiIwMDAwIiwicmV0dXJuTXNnIjoiT0siLCJzdGF0ZUNvZGUiOiJTIiwid29ya0lkIjoibi1kNzRlZDIwMC1hMjM0LTExZWItOGFlMC0wMDUxZWRhODNlNTAiLCJkZXZpY2VTdGF0ZSI6IkUiLCJ0aW1lc3RhbXAiOjB9fQ==","createdAt":1631073471.1093121,"header":{"entries":[{"key":{"name":"Date","nameInLowercase":"date"},"value":"Wed, 08 Sep 2021 03:57:50 GMT","isNewEntry":false},{"key":{"name":"Server","nameInLowercase":"server"},"value":"Apache","isNewEntry":false},{"key":{"name":"X-dynaTrace-JS-Agent","nameInLowercase":"x-dynatrace-js-agent"},"value":"true","isNewEntry":false},{"key":{"name":"X-Powered-By","nameInLowercase":"x-powered-by"},"value":"","isNewEntry":false},{"key":{"name":"Content-Length","nameInLowercase":"content-length"},"value":"148","isNewEntry":false},{"key":{"name":"Access-Control-Allow-Origin","nameInLowercase":"access-control-allow-origin"},"value":"https:\/\/appassets.lgthinqapp.net","isNewEntry":false},{"key":{"name":"Access-Control-Allow-Headers","nameInLowercase":"access-control-allow-headers"},"value":"*","isNewEntry":false},{"key":{"name":"Connection","nameInLowercase":"connection"},"value":"close","isNewEntry":false},{"key":{"name":"Content-Type","nameInLowercase":"content-type"},"value":"application\/json;charset=utf-8","isNewEntry":false}]},"error":null,"version":{"major":1,"minor":1}},"client":null,"name":"266","isFromFile":false}

**Comment by nVuln** [comment]
try turn on/off ice plus on LG app, and find request to url `/api/rti/rtiControl` , look into `body` tab and see what they sent

**Comment by blitzdakka** [comment]
Yup I have four requests that include rtiControl:

274:
{"id":"274","isIntercepted":true,"fileName":null,"style":null,"requestEndAt":null,"isUnderNetworkCondition":false,"isRelayed":false,"remoteDevice":{"ip":"127.0.0.1","name":"127.0.0.1"},"createAt":1631073474.8750138,"isSSL":true,"endAt":null,"summary":{"serverIpAddress":"","clientPort":57907,"clientIpAddress":"127.0.0.1","serverPort":0},"proxyCreatedAt":1631073474.874788,"websocketMessageStorage":null,"request":{"port":46030,"method":{"name":"POST"},"header":{"entries":[{"key":{"name":"Host","nameInLowercase":"host"},"value":"kic.lgthinq.com:46030","isNewEntry":false},{"key":{"name":"Cookie","nameInLowercase":"cookie"},"value":"dtCookie=76B1D6D3CD838747AF8A1EC018373682|X2RlZmF1bHR8MQ","isNewEntry":false},{"key":{"name":"User-Agent","nameInLowercase":"user-agent"},"value":"Mozilla\/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit\/605.1.15 (KHTML, like Gecko) Mobile\/15E148","isNewEntry":false},{"key":{"name":"Accept-Encoding","nameInLowercase":"accept-encoding"},"value":"gzip, deflate, br","isNewEntry":false},{"key":{"name":"x-thinq-app-ver","nameInLowercase":"x-thinq-app-ver"},"value":"3.6.1200","isNewEntry":false},{"key":{"name":"x-thinq-app-type","nameInLowercase":"x-thinq-app-type"},"value":"NUTS","isNewEntry":false},{"key":{"name":"x-language-code","nameInLowercase":"x-language-code"},"value":"en-AU","isNewEntry":false},{"key":{"name":"Origin","nameInLowercase":"origin"},"value":"file:\/\/","isNewEntry":false},{"key":{"name":"x-client-id","nameInLowercase":"x-client-id"},"value":"00f38e1e7e1859b8892c25cde99c25e0fac55514e3c651c659bf455425573774","isNewEntry":false},{"key":{"name":"x-thinq-app-level","nameInLowercase":"x-thinq-app-level"},"value":"PRD","isNewEntry":false},{"key":{"name":"Content-Length","nameInLowercase":"content-length"},"value":"207","isNewEntry":false},{"key":{"name":"Connection","nameInLowercase":"connection"},"value":"keep-alive","isNewEntry":false},{"key":{"name":"x-user-no","nameInLowercase":"x-user-no"},"value":"AU2108204318026","isNewEntry":false},{"key":{"name":"x-service-code","nameInLowercase":"x-service-code"},"value":"SVC202","isNewEntry":false},{"key":{"name":"Accept-Language","nameInLowercase":"accept-language"},"value":"en-au","isNewEntry":false},{"key":{"name":"x-message-id","nameInLowercase":"x-message-id"},"value":"SpEeUTZbFKiNTJXv56xngF","isNewEntry":false},{"key":{"name":"x-emp-token","nameInLowercase":"x-emp-token"},"value":"2e1fc58fd1f6f2f0b897b5c7e6f60cf99926ecc9c93a1304679acf116123f04a9dcf687005655d04b12880265f748c37","isNewEntry":false},{"key":{"name":"Accept","nameInLowercase":"accept"},"value":"application\/json","isNewEntry":false},{"key":{"name":"Content-Type","nameInLowercase":"content-type"},"value":"application\/json;charset=UTF-8","isNewEntry":false},{"key":{"name":"x-api-key","nameInLowercase":"x-api-key"},"value":"VGhpblEyLjAgU0VSVklDRQ==","isNewEntry":false},{"key":{"name":"x-thinq-app-os","nameInLowercase":"x-thinq-app-os"},"value":"IOS","isNewEntry":false},{"key":{"name":"x-country-code","nameInLowercase":"x-country-code"},"value":"AU","isNewEntry":false},{"key":{"name":"x-service-phase","nameInLowercase":"x-service-phase"},"value":"OP","isNewEntry":false}]},"fullPath":"https:\/\/kic.lgthinq.com:46030\/api\/rti\/rtiControl","scheme":"https","isWebSocketUpgrade":false,"isSSL":true,"host":"kic.lgthinq.com","version":{"major":1,"minor":1},"uri":"\/api\/rti\/rtiControl","bodyData":"eyJsZ2VkbVJvb3QiOnsiZGV2aWNlSWQiOiJkNzRlZDIwMC1hMjM0LTExZWItOGFlMC0wMDUxZWRhODNlNTAiLCJ3b3JrSWQiOiI5MWEyZWUxMS01MmViLTljNjQtOTdiYy01YmY5MDFmMTBiNGEiLCJjbWQiOiJDb250cm9sIiwiY21kT3B0IjoiU2V0IiwidmFsdWUiOiJDb250cm9sRGF0YSIsImRhdGEiOiJBZ0VCLy8vLy8vLy8vLzg9IiwiZm9ybWF0IjoiQjY0In19"},"response":{"status":{"phrase":"OK","strict":false,"code":200},"bodyData":"eyJsZ2VkbVJvb3QiOnsicmV0dXJuQ2QiOiIwMDAwIiwicmV0dXJuTXNnIjoiT0siLCJkZXZpY2VJZCI6ImQ3NGVkMjAwLWEyMzQtMTFlYi04YWUwLTAwNTFlZGE4M2U1MCIsInN0YXRlQ29kZSI6IlMiLCJ3b3JrSWQiOiJuLTkxYTJlZTExLTUyZWItOWM2NC05N2JjLTViZjkwMWYxMGIiLCJmb3JtYXQiOiJCNjQiLCJkZXZpY2VTdGF0ZSI6IkUiLCJ0aW1lc3RhbXAiOjB9fQ==","createdAt":1631073476.936904,"header":{"entries":[{"key":{"name":"Date","nameInLowercase":"date"},"value":"Wed, 08 Sep 2021 03:57:55 GMT","isNewEntry":false},{"key":{"name":"Server","nameInLowercase":"server"},"value":"Apache","isNewEntry":false},{"key":{"name":"X-dynaTrace-JS-Agent","nameInLowercase":"x-dynatrace-js-agent"},"value":"true","isNewEntry":false},{"key":{"name":"X-Powered-By","nameInLowercase":"x-powered-by"},"value":"","isNewEntry":false},{"key":{"name":"Content-Length","nameInLowercase":"content-length"},"value":"211","isNewEntry":false},{"key":{"name":"Access-Control-Allow-Origin","nameInLowercase":"access-control-allow-origin"},"value":"https:\/\/appassets.lgthinqapp.net","isNewEntry":false},{"key":{"name":"Access-Control-Allow-Headers","nameInLowercase":"access-control-allow-headers"},"value":"*","isNewEntry":false},{"key":{"name":"Connection","nameInLowercase":"connection"},"value":"close","isNewEntry":false},{"key":{"name":"Content-Type","nameInLowercase":"content-type"},"value":"application\/json;charset=utf-8","isNewEntry":false}]},"error":null,"version":{"major":1,"minor":1}},"client":null,"name":"274","isFromFile":false}

291:
{"id":"291","isIntercepted":true,"fileName":null,"style":null,"requestEndAt":null,"isUnderNetworkCondition":false,"isRelayed":false,"remoteDevice":{"ip":"127.0.0.1","name":"127.0.0.1"},"createAt":1631073480.9294319,"isSSL":true,"endAt":null,"summary":{"serverIpAddress":"","clientPort":57943,"clientIpAddress":"127.0.0.1","serverPort":0},"proxyCreatedAt":1631073480.9292111,"websocketMessageStorage":null,"request":{"port":46030,"method":{"name":"POST"},"header":{"entries":[{"key":{"name":"Host","nameInLowercase":"host"},"value":"kic.lgthinq.com:46030","isNewEntry":false},{"key":{"name":"Cookie","nameInLowercase":"cookie"},"value":"dtCookie=76B1D6D3CD838747AF8A1EC018373682|X2RlZmF1bHR8MQ","isNewEntry":false},{"key":{"name":"User-Agent","nameInLowercase":"user-agent"},"value":"Mozilla\/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit\/605.1.15 (KHTML, like Gecko) Mobile\/15E148","isNewEntry":false},{"key":{"name":"Accept-Encoding","nameInLowercase":"accept-encoding"},"value":"gzip, deflate, br","isNewEntry":false},{"key":{"name":"x-thinq-app-ver","nameInLowercase":"x-thinq-app-ver"},"value":"3.6.1200","isNewEntry":false},{"key":{"name":"x-thinq-app-type","nameInLowercase":"x-thinq-app-type"},"value":"NUTS","isNewEntry":false},{"key":{"name":"x-language-code","nameInLowercase":"x-language-code"},"value":"en-AU","isNewEntry":false},{"key":{"name":"Origin","nameInLowercase":"origin"},"value":"file:\/\/","isNewEntry":false},{"key":{"name":"x-client-id","nameInLowercase":"x-client-id"},"value":"00f38e1e7e1859b8892c25cde99c25e0fac55514e3c651c659bf455425573774","isNewEntry":false},{"key":{"name":"x-thinq-app-level","nameInLowercase":"x-thinq-app-level"},"value":"PRD","isNewEntry":false},{"key":{"name":"Content-Length","nameInLowercase":"content-length"},"value":"207","isNewEntry":false},{"key":{"name":"Connection","nameInLowercase":"connection"},"value":"keep-alive","isNewEntry":false},{"key":{"name":"x-user-no","nameInLowercase":"x-user-no"},"value":"AU2108204318026","isNewEntry":false},{"key":{"name":"x-service-code","nameInLowercase":"x-service-code"},"value":"SVC202","isNewEntry":false},{"key":{"name":"Accept-Language","nameInLowercase":"accept-language"},"value":"en-au","isNewEntry":false},{"key":{"name":"x-message-id","nameInLowercase":"x-message-id"},"value":"IW0OrybLHsuCSDIR_zvd0V","isNewEntry":false},{"key":{"name":"x-emp-token","nameInLowercase":"x-emp-token"},"value":"2e1fc58fd1f6f2f0b897b5c7e6f60cf99926ecc9c93a1304679acf116123f04a9dcf687005655d04b12880265f748c37","isNewEntry":false},{"key":{"name":"Accept","nameInLowercase":"accept"},"value":"application\/json","isNewEntry":false},{"key":{"name":"Content-Type","nameInLowercase":"content-type"},"value":"application\/json;charset=UTF-8","isNewEntry":false},{"key":{"name":"x-api-key","nameInLowercase":"x-api-key"},"value":"VGhpblEyLjAgU0VSVklDRQ==","isNewEntry":false},{"key":{"name":"x-thinq-app-os","nameInLowercase":"x-thinq-app-os"},"value":"IOS","isNewEntry":false},{"key":{"name":"x-country-code","nameInLowercase":"x-country-code"},"value":"AU","isNewEntry":false},{"key":{"name":"x-service-phase","nameInLowercase":"x-service-phase"},"value":"OP","isNewEntry":false}]},"fullPath":"https:\/\/kic.lgthinq.com:46030\/api\/rti\/rtiControl","scheme":"https","isWebSocketUpgrade":false,"isSSL":true,"host":"kic.lgthinq.com","version":{"major":1,"minor":1},"uri":"\/api\/rti\/rtiControl","bodyData":"eyJsZ2VkbVJvb3QiOnsiZGV2aWNlSWQiOiJkNzRlZDIwMC1hMjM0LTExZWItOGFlMC0wMDUxZWRhODNlNTAiLCJ3b3JrSWQiOiIzM2UyYjFmZC1lM2RkLTYyMDYtYTcxOC04MTkzNjI1Y2FhYmEiLCJjbWQiOiJDb250cm9sIiwiY21kT3B0IjoiU2V0IiwidmFsdWUiOiJDb250cm9sRGF0YSIsImRhdGEiOiJBZ0VDLy8vLy8vLy8vLzg9IiwiZm9ybWF0IjoiQjY0In19"},"response":{"status":{"phrase":"OK","strict":false,"code":200},"bodyData":"eyJsZ2VkbVJvb3QiOnsicmV0dXJuQ2QiOiIwMDAwIiwicmV0dXJuTXNnIjoiT0siLCJkZXZpY2VJZCI6ImQ3NGVkMjAwLWEyMzQtMTFlYi04YWUwLTAwNTFlZGE4M2U1MCIsInN0YXRlQ29kZSI6IlMiLCJ3b3JrSWQiOiJuLTMzZTJiMWZkLWUzZGQtNjIwNi1hNzE4LTgxOTM2MjVjYWEiLCJmb3JtYXQiOiJCNjQiLCJkZXZpY2VTdGF0ZSI6IkUiLCJ0aW1lc3RhbXAiOjB9fQ==","createdAt":1631073482.714767,"header":{"entries":[{"key":{"name":"Date","nameInLowercase":"date"},"value":"Wed, 08 Sep 2021 03:58:01 GMT","isNewEntry":false},{"key":{"name":"Server","nameInLowercase":"server"},"value":"Apache","isNewEntry":false},{"key":{"name":"X-dynaTrace-JS-Agent","nameInLowercase":"x-dynatrace-js-agent"},"value":"true","isNewEntry":false},{"key":{"name":"X-Powered-By","nameInLowercase":"x-powered-by"},"value":"","isNewEntry":false},{"key":{"name":"Content-Length","nameInLowercase":"content-length"},"value":"211","isNewEntry":false},{"key":{"name":"Access-Control-Allow-Origin","nameInLowercase":"access-control-allow-origin"},"value":"https:\/\/appassets.lgthinqapp.net","isNewEntry":false},{"key":{"name":"Access-Control-Allow-Headers","nameInLowercase":"access-control-allow-headers"},"value":"*","isNewEntry":false},{"key":{"name":"Connection","nameInLowercase":"connection"},"value":"close","isNewEntry":false},{"key":{"name":"Content-Type","nameInLowercase":"content-type"},"value":"application\/json;charset=utf-8","isNewEntry":false}]},"error":null,"version":{"major":1,"minor":1}},"client":null,"name":"291","isFromFile":false}

319:
{"id":"319","isIntercepted":true,"fileName":null,"style":null,"requestEndAt":null,"isUnderNetworkCondition":false,"isRelayed":false,"remoteDevice":{"ip":"127.0.0.1","name":"127.0.0.1"},"createAt":1631073496.2311769,"isSSL":true,"endAt":null,"summary":{"serverIpAddress":"","clientPort":58000,"clientIpAddress":"127.0.0.1","serverPort":0},"proxyCreatedAt":1631073496.2310171,"websocketMessageStorage":null,"request":{"port":46030,"method":{"name":"POST"},"header":{"entries":[{"key":{"name":"Host","nameInLowercase":"host"},"value":"kic.lgthinq.com:46030","isNewEntry":false},{"key":{"name":"Cookie","nameInLowercase":"cookie"},"value":"dtCookie=76B1D6D3CD838747AF8A1EC018373682|X2RlZmF1bHR8MQ","isNewEntry":false},{"key":{"name":"User-Agent","nameInLowercase":"user-agent"},"value":"Mozilla\/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit\/605.1.15 (KHTML, like Gecko) Mobile\/15E148","isNewEntry":false},{"key":{"name":"Accept-Encoding","nameInLowercase":"accept-encoding"},"value":"gzip, deflate, br","isNewEntry":false},{"key":{"name":"x-thinq-app-ver","nameInLowercase":"x-thinq-app-ver"},"value":"3.6.1200","isNewEntry":false},{"key":{"name":"x-thinq-app-type","nameInLowercase":"x-thinq-app-type"},"value":"NUTS","isNewEntry":false},{"key":{"name":"x-language-code","nameInLowercase":"x-language-code"},"value":"en-AU","isNewEntry":false},{"key":{"name":"Origin","nameInLowercase":"origin"},"value":"file:\/\/","isNewEntry":false},{"key":{"name":"x-client-id","nameInLowercase":"x-client-id"},"value":"00f38e1e7e1859b8892c25cde99c25e0fac55514e3c651c659bf455425573774","isNewEntry":false},{"key":{"name":"x-thinq-app-level","nameInLowercase":"x-thinq-app-level"},"value":"PRD","isNewEntry":false},{"key":{"name":"Content-Length","nameInLowercase":"content-length"},"value":"207","isNewEntry":false},{"key":{"name":"Connection","nameInLowercase":"connection"},"value":"keep-alive","isNewEntry":false},{"key":{"name":"x-user-no","nameInLowercase":"x-user-no"},"value":"AU2108204318026","isNewEntry":false},{"key":{"name":"x-service-code","nameInLowercase":"x-service-code"},"value":"SVC202","isNewEntry":false},{"key":{"name":"Accept-Language","nameInLowercase":"accept-language"},"value":"en-au","isNewEntry":false},{"key":{"name":"x-message-id","nameInLowercase":"x-message-id"},"value":"ogAWydSxFzDDUSJPMrwubV","isNewEntry":false},{"key":{"name":"x-emp-token","nameInLowercase":"x-emp-token"},"value":"2e1fc58fd1f6f2f0b897b5c7e6f60cf99926ecc9c93a1304679acf116123f04a9dcf687005655d04b12880265f748c37","isNewEntry":false},{"key":{"name":"Accept","nameInLowercase":"accept"},"value":"application\/json","isNewEntry":false},{"key":{"name":"Content-Type","nameInLowercase":"content-type"},"value":"application\/json;charset=UTF-8","isNewEntry":false},{"key":{"name":"x-api-key","nameInLowercase":"x-api-key"},"value":"VGhpblEyLjAgU0VSVklDRQ==","isNewEntry":false},{"key":{"name":"x-thinq-app-os","nameInLowercase":"x-thinq-app-os"},"value":"IOS","isNewEntry":false},{"key":{"name":"x-country-code","nameInLowercase":"x-country-code"},"value":"AU","isNewEntry":false},{"key":{"name":"x-service-phase","nameInLowercase":"x-service-phase"},"value":"OP","isNewEntry":false}]},"fullPath":"https:\/\/kic.lgthinq.com:46030\/api\/rti\/rtiControl","scheme":"https","isWebSocketUpgrade":false,"isSSL":true,"host":"kic.lgthinq.com","version":{"major":1,"minor":1},"uri":"\/api\/rti\/rtiControl","bodyData":"eyJsZ2VkbVJvb3QiOnsiZGV2aWNlSWQiOiJkNzRlZDIwMC1hMjM0LTExZWItOGFlMC0wMDUxZWRhODNlNTAiLCJ3b3JrSWQiOiJiNTMxNzc1Yi0yZDFiLWViYmEtNTAwNi01ODUyNmNjZDcwNmQiLCJjbWQiOiJDb250cm9sIiwiY21kT3B0IjoiU2V0IiwidmFsdWUiOiJDb250cm9sRGF0YSIsImRhdGEiOiJBd0VDLy8vLy8vLy8vLzg9IiwiZm9ybWF0IjoiQjY0In19"},"response":{"status":{"phrase":"OK","strict":false,"code":200},"bodyData":"eyJsZ2VkbVJvb3QiOnsicmV0dXJuQ2QiOiIwMDAwIiwicmV0dXJuTXNnIjoiT0siLCJkZXZpY2VJZCI6ImQ3NGVkMjAwLWEyMzQtMTFlYi04YWUwLTAwNTFlZGE4M2U1MCIsInN0YXRlQ29kZSI6IlMiLCJ3b3JrSWQiOiJuLWI1MzE3NzViLTJkMWItZWJiYS01MDA2LTU4NTI2Y2NkNzAiLCJmb3JtYXQiOiJCNjQiLCJkZXZpY2VTdGF0ZSI6IkUiLCJ0aW1lc3RhbXAiOjB9fQ==","createdAt":1631073498.029171,"header":{"entries":[{"key":{"name":"Date","nameInLowercase":"date"},"value":"Wed, 08 Sep 2021 03:58:17 GMT","isNewEntry":false},{"key":{"name":"Server","nameInLowercase":"server"},"value":"Apache","isNewEntry":false},{"key":{"name":"X-dynaTrace-JS-Agent","nameInLowercase":"x-dynatrace-js-agent"},"value":"true","isNewEntry":false},{"key":{"name":"X-Powered-By","nameInLowercase":"x-powered-by"},"value":"","isNewEntry":false},{"key":{"name":"Content-Length","nameInLowercase":"content-length"},"value":"211","isNewEntry":false},{"key":{"name":"Access-Control-Allow-Origin","nameInLowercase":"access-control-allow-origin"},"value":"https:\/\/appassets.lgthinqapp.net","isNewEntry":false},{"key":{"name":"Access-Control-Allow-Headers","nameInLowercase":"access-control-allow-headers"},"value":"*","isNewEntry":false},{"key":{"name":"Connection","nameInLowercase":"connection"},"value":"close","isNewEntry":false},{"key":{"name":"Content-Type","nameInLowercase":"content-type"},"value":"application\/json;charset=utf-8","isNewEntry":false}]},"error":null,"version":{"major":1,"minor":1}},"client":null,"name":"319","isFromFile":false}

342:
{"id":"342","isIntercepted":true,"fileName":null,"style":null,"requestEndAt":null,"isUnderNetworkCondition":false,"isRelayed":false,"remoteDevice":{"ip":"127.0.0.1","name":"127.0.0.1"},"createAt":1631073504.4835029,"isSSL":true,"endAt":null,"summary":{"serverIpAddress":"","clientPort":58047,"clientIpAddress":"127.0.0.1","serverPort":0},"proxyCreatedAt":1631073504.483299,"websocketMessageStorage":null,"request":{"port":46030,"method":{"name":"POST"},"header":{"entries":[{"key":{"name":"Host","nameInLowercase":"host"},"value":"kic.lgthinq.com:46030","isNewEntry":false},{"key":{"name":"Cookie","nameInLowercase":"cookie"},"value":"dtCookie=76B1D6D3CD838747AF8A1EC018373682|X2RlZmF1bHR8MQ","isNewEntry":false},{"key":{"name":"User-Agent","nameInLowercase":"user-agent"},"value":"Mozilla\/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit\/605.1.15 (KHTML, like Gecko) Mobile\/15E148","isNewEntry":false},{"key":{"name":"Accept-Encoding","nameInLowercase":"accept-encoding"},"value":"gzip, deflate, br","isNewEntry":false},{"key":{"name":"x-thinq-app-ver","nameInLowercase":"x-thinq-app-ver"},"value":"3.6.1200","isNewEntry":false},{"key":{"name":"x-thinq-app-type","nameInLowercase":"x-thinq-app-type"},"value":"NUTS","isNewEntry":false},{"key":{"name":"x-language-code","nameInLowercase":"x-language-code"},"value":"en-AU","isNewEntry":false},{"key":{"name":"Origin","nameInLowercase":"origin"},"value":"file:\/\/","isNewEntry":false},{"key":{"name":"x-client-id","nameInLowercase":"x-client-id"},"value":"00f38e1e7e1859b8892c25cde99c25e0fac55514e3c651c659bf455425573774","isNewEntry":false},{"key":{"name":"x-thinq-app-level","nameInLowercase":"x-thinq-app-level"},"value":"PRD","isNewEntry":false},{"key":{"name":"Content-Length","nameInLowercase":"content-length"},"value":"207","isNewEntry":false},{"key":{"name":"Connection","nameInLowercase":"connection"},"value":"keep-alive","isNewEntry":false},{"key":{"name":"x-user-no","nameInLowercase":"x-user-no"},"value":"AU2108204318026","isNewEntry":false},{"key":{"name":"x-service-code","nameInLowercase":"x-service-code"},"value":"SVC202","isNewEntry":false},{"key":{"name":"Accept-Language","nameInLowercase":"accept-language"},"value":"en-au","isNewEntry":false},{"key":{"name":"x-message-id","nameInLowercase":"x-message-id"},"value":"Emr__zyGGAyvY0WoJMV8LF","isNewEntry":false},{"key":{"name":"x-emp-token","nameInLowercase":"x-emp-token"},"value":"2e1fc58fd1f6f2f0b897b5c7e6f60cf99926ecc9c93a1304679acf116123f04a9dcf687005655d04b12880265f748c37","isNewEntry":false},{"key":{"name":"Accept","nameInLowercase":"accept"},"value":"application\/json","isNewEntry":false},{"key":{"name":"Content-Type","nameInLowercase":"content-type"},"value":"application\/json;charset=UTF-8","isNewEntry":false},{"key":{"name":"x-api-key","nameInLowercase":"x-api-key"},"value":"VGhpblEyLjAgU0VSVklDRQ==","isNewEntry":false},{"key":{"name":"x-thinq-app-os","nameInLowercase":"x-thinq-app-os"},"value":"IOS","isNewEntry":false},{"key":{"name":"x-country-code","nameInLowercase":"x-country-code"},"value":"AU","isNewEntry":false},{"key":{"name":"x-service-phase","nameInLowercase":"x-service-phase"},"value":"OP","isNewEntry":false}]},"fullPath":"https:\/\/kic.lgthinq.com:46030\/api\/rti\/rtiControl","scheme":"https","isWebSocketUpgrade":false,"isSSL":true,"host":"kic.lgthinq.com","version":{"major":1,"minor":1},"uri":"\/api\/rti\/rtiControl","bodyData":"eyJsZ2VkbVJvb3QiOnsiZGV2aWNlSWQiOiJkNzRlZDIwMC1hMjM0LTExZWItOGFlMC0wMDUxZWRhODNlNTAiLCJ3b3JrSWQiOiJmMTc1NjNhMy1mNDc1LTk1YjEtNjY5OS1iMGY3YjFhY2ViZjMiLCJjbWQiOiJDb250cm9sIiwiY21kT3B0IjoiU2V0IiwidmFsdWUiOiJDb250cm9sRGF0YSIsImRhdGEiOiJBd0VCLy8vLy8vLy8vLzg9IiwiZm9ybWF0IjoiQjY0In19"},"response":{"status":{"phrase":"OK","strict":false,"code":200},"bodyData":"eyJsZ2VkbVJvb3QiOnsicmV0dXJuQ2QiOiIwMDAwIiwicmV0dXJuTXNnIjoiT0siLCJkZXZpY2VJZCI6ImQ3NGVkMjAwLWEyMzQtMTFlYi04YWUwLTAwNTFlZGE4M2U1MCIsInN0YXRlQ29kZSI6IlMiLCJ3b3JrSWQiOiJuLWYxNzU2M2EzLWY0NzUtOTViMS02Njk5LWIwZjdiMWFjZWIiLCJmb3JtYXQiOiJCNjQiLCJkZXZpY2VTdGF0ZSI6IkUiLCJ0aW1lc3RhbXAiOjB9fQ==","createdAt":1631073506.0326529,"header":{"entries":[{"key":{"name":"Date","nameInLowercase":"date"},"value":"Wed, 08 Sep 2021 03:58:25 GMT","isNewEntry":false},{"key":{"name":"Server","nameInLowercase":"server"},"value":"Apache","isNewEntry":false},{"key":{"name":"X-dynaTrace-JS-Agent","nameInLowercase":"x-dynatrace-js-agent"},"value":"true","isNewEntry":false},{"key":{"name":"X-Powered-By","nameInLowercase":"x-powered-by"},"value":"","isNewEntry":false},{"key":{"name":"Content-Length","nameInLowercase":"content-length"},"value":"211","isNewEntry":false},{"key":{"name":"Access-Control-Allow-Origin","nameInLowercase":"access-control-allow-origin"},"value":"https:\/\/appassets.lgthinqapp.net","isNewEntry":false},{"key":{"name":"Access-Control-Allow-Headers","nameInLowercase":"access-control-allow-headers"},"value":"*","isNewEntry":false},{"key":{"name":"Connection","nameInLowercase":"connection"},"value":"close","isNewEntry":false},{"key":{"name":"Content-Type","nameInLowercase":"content-type"},"value":"application\/json;charset=utf-8","isNewEntry":false}]},"error":null,"version":{"major":1,"minor":1}},"client":null,"name":"342","isFromFile":false}

**Comment by nVuln** [comment]
just confirm, your TempRefrigerator = 5 and TempFreezer = -16 ?

**Comment by blitzdakka** [comment]
Correct, when I generated those logs I did the following:

- Turned express freeze on
- Changed fridge from 4 to 5
- Turned express freeze off
- Changed fridge from 5 back to 4

Freezer was left on -16 the whole time.

**Comment by nVuln** [comment]
thanks for your help, `v1.2.0-test.15` is published now, please test

**Comment by blitzdakka** [comment]
Very close now! Connection to HomeKit all works fine and no more errors in HB. I can turn express freeze on/off via HomeKit and it works perfectly. I can also change the temperature which works, but after the refresh HomeKit gets the wrong figure. E.g. I can set the freezer to -16 and it updates correctly on the fridge, but after a minute the app temperature changes and reads -19, even though the fridge is still correctly set to -16.

**Comment by nVuln** [comment]
> Very close now! Connection to HomeKit all works fine and no more errors in HB. I can turn express freeze on/off via HomeKit and it works perfectly. I can also change the temperature which works, but after the refresh HomeKit gets the wrong figure. E.g. I can set the freezer to -16 and it updates correctly on the fridge, but after a minute the app temperature changes and reads -19, even though the fridge is still correctly set to -16.

in homekit, is temperature showing correct before adjust ? after adjust, it's keep -19 forever ?

**Comment by blitzdakka** [comment]
Nah it shows incorrect, I adjust it and the temp on the fridge matches what I set it to, then after a bit (assuming the next refresh) the temp in HomeKit goes back to the incorrect value.

**Comment by nVuln** [comment]
> Nah it shows incorrect, I adjust it and the temp on the fridge matches what I set it to, then after a bit (assuming the next refresh) the temp in HomeKit goes back to the incorrect value.

found issue, please try again `v1.2.0-test.16`

**Comment by blitzdakka** [comment]
New error pasted below, this occurred before I even changed anything.

The freezer portion seems to work fine now, but the fridge is off by 1, and does the same thing where it moves to the correct temp and then reverts to the incorrect value in HomeKit after a minute.

Also the little temperature widget at the top of the HomeKit room seems to have completely incorrect values.

[08/09/2021, 9:51:40 pm] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 0 exceeded maximum of -16. See https://git.io/JtMGR for more info.
[08/09/2021, 9:51:40 pm] [homebridge-lg-thinq] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1950:16)
    at TargetTemperature.Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at Thermostat.Service.updateCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at Refrigerator.updateAccessoryCharacteristic (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:104:25)
    at EventEmitter.emit (events.js:400:28)
    at /usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:167:25
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by nVuln** [comment]
fixed some bug in `vv1.2.0-test.17`, hope it's worked

**Comment by blitzdakka** [comment]
Works perfectly, you legend! Really appreciate the effort you've gone to, will drop some money in your donation box :)

Should I just stay on the test version until the next release?

**Comment by nVuln** [comment]
> Works perfectly, you legend! Really appreciate the effort you've gone to, will drop some money in your donation box :)

thank you so much

> Should I just stay on the test version until the next release?

I already published `v1.1.5`, please update

if you got any error, please open new issue
